// ── Document Generator for Start Your Cause ──
// Generates actual nonprofit formation documents as text/HTML for download

function generateAllDocs(answers, stateData) {
  return {
    articles: generateArticles(answers, stateData),
    bylaws: generateBylaws(answers, stateData),
    conflictPolicy: generateConflictPolicy(answers),
    boardMinutes: generateBoardMinutes(answers, stateData),
    missionStatement: generateMissionStatement(answers),
    ein_checklist: generateEINChecklist(answers, stateData),
    irs_prep: generateIRSPrep(answers, stateData),
    stateChecklist: generateStateChecklist(answers, stateData),
  };
}

function today() {
  return new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
}

function docHeader(title, subtitle) {
  return `<!DOCTYPE html><html><head><meta charset="UTF-8">
<title>${title}</title>
<style>
  body { font-family: 'Times New Roman', Times, serif; max-width: 750px; margin: 40px auto; padding: 0 2rem 4rem; color: #1a1a1a; font-size: 12pt; line-height: 1.7; }
  h1 { text-align: center; font-size: 16pt; margin-bottom: 4px; text-transform: uppercase; letter-spacing: 1px; }
  h2 { font-size: 13pt; margin-top: 2em; margin-bottom: 4px; text-transform: uppercase; }
  h3 { font-size: 12pt; margin-top: 1.5em; margin-bottom: 4px; }
  .center { text-align: center; }
  .underline { text-decoration: underline; }
  .section { margin-bottom: 1.5em; }
  .blank { display: inline-block; min-width: 180px; border-bottom: 1px solid #000; }
  .sig-line { margin-top: 3em; border-top: 1px solid #000; width: 280px; padding-top: 4px; font-size: 11pt; }
  .notice { background: #fffbe6; border: 1px solid #e0c84a; padding: 12px 16px; font-size: 11pt; margin-bottom: 1.5em; border-radius: 4px; font-family: Arial, sans-serif; }
  .print-btn { font-family: Arial; background: #2d8f6f; color: #fff; border: none; padding: 10px 24px; border-radius: 6px; font-size: 13px; cursor: pointer; margin-bottom: 24px; }
  @media print { .print-btn, .notice { display: none; } }
  p { margin: 0 0 0.75em; }
  ol { margin-left: 1.5em; }
  li { margin-bottom: 0.4em; }
</style></head><body>
<button class="print-btn" onclick="window.print()">🖨 Print / Save as PDF</button>
<div class="notice">⚠️ <strong>Important:</strong> This document is a starting template generated by Start Your Cause. It is NOT a substitute for legal advice. Have a licensed attorney review all documents before filing. Some states have specific required language.</div>
<h1>${title}</h1>
<p class="center" style="margin-bottom:2em">${subtitle}</p>`;
}

const docFooter = `</body></html>`;

// ── 1. ARTICLES OF INCORPORATION ──
function generateArticles(a, sd) {
  const stName = sd ? sd.form : "Articles of Incorporation (Nonprofit)";
  const stAgency = sd ? sd.agency : "[State Agency]";
  const stState = a.state || "[State]";
  const stFee = sd ? `$${sd.fee}` : "[Fee]";

  return docHeader(stName, `State of ${stState} | Filing Fee: ${stFee}<br>File with: ${stAgency}`) + `

<div class="section">
<h2>Article I — Name</h2>
<p>The name of this nonprofit corporation is: <strong>${a.orgName || "[Organization Name]"}</strong></p>
</div>

<div class="section">
<h2>Article II — Registered Agent</h2>
<p>The registered agent of this corporation, who has an address in the State of ${stState}, is:</p>
<p>Name: <span class="blank">&nbsp;</span></p>
<p>Address: <span class="blank" style="min-width:300px">&nbsp;</span></p>
<p>City, State, ZIP: <span class="blank" style="min-width:300px">&nbsp;</span></p>
</div>

<div class="section">
<h2>Article III — Purpose</h2>
<p>This corporation is organized exclusively for charitable, educational, religious, and/or scientific purposes within the meaning of Section 501(c)(3) of the Internal Revenue Code (or the corresponding section of any future federal tax code).</p>
<p>Specifically, the purpose of this corporation is:</p>
<p><em>${a.activities || "[Describe your nonprofit's specific purpose and activities here]"}</em></p>
<p>The corporation will primarily serve: <em>${a.whoHelp || "[Describe who you serve]"}</em></p>
<p>Geographic area served: <em>${a.location || "[City, County, State, or National]"}</em></p>
</div>

<div class="section">
<h2>Article IV — Nonprofit Status</h2>
<p>This corporation is organized as a nonprofit corporation. No part of the net earnings of the corporation shall inure to the benefit of, or be distributable to its members, trustees, officers, directors, or other private persons, except that the corporation shall be authorized and empowered to pay reasonable compensation for services rendered and to make payments and distributions in furtherance of the purposes set forth in Article III hereof.</p>
</div>

<div class="section">
<h2>Article V — Political Activity</h2>
<p>No substantial part of the activities of the corporation shall be the carrying on of propaganda, or otherwise attempting to influence legislation (except as otherwise permitted by IRC Section 501(h)), and the corporation shall not participate in, or intervene in (including the publishing or distribution of statements), any political campaign on behalf of or in opposition to any candidate for public office.</p>
</div>

<div class="section">
<h2>Article VI — Dissolution</h2>
<p>Upon the dissolution of this corporation, assets shall be distributed for one or more exempt purposes within the meaning of section 501(c)(3) of the Internal Revenue Code, or the corresponding section of any future federal tax code, or shall be distributed to the federal government, or to a state or local government, for a public purpose. Any such assets not so disposed of shall be disposed of by a Court of Competent Jurisdiction of the county in which the principal office of the corporation is then located, exclusively for such purposes or to such organization or organizations, as said Court shall determine, which are organized and operated exclusively for such purposes.</p>
</div>

<div class="section">
<h2>Article VII — Incorporators</h2>
<p>The names and addresses of the incorporators are:</p>
<p>1. Name: <strong>${a.founderName || "[Founder Name]"}</strong><br>
&nbsp;&nbsp;&nbsp;Email: ${a.founderEmail || "[Email]"}<br>
&nbsp;&nbsp;&nbsp;Address: <span class="blank" style="min-width:350px">&nbsp;</span></p>
<p>2. Name: <strong>${a.board2 || "[Board Member 2]"}</strong><br>
&nbsp;&nbsp;&nbsp;Address: <span class="blank" style="min-width:350px">&nbsp;</span></p>
<p>3. Name: <strong>${a.board3 || "[Board Member 3]"}</strong><br>
&nbsp;&nbsp;&nbsp;Address: <span class="blank" style="min-width:350px">&nbsp;</span></p>
${a.board4 ? `<p>4. Name: <strong>${a.board4}</strong><br>&nbsp;&nbsp;&nbsp;Address: <span class="blank" style="min-width:350px">&nbsp;</span></p>` : ''}
${a.board5 ? `<p>5. Name: <strong>${a.board5}</strong><br>&nbsp;&nbsp;&nbsp;Address: <span class="blank" style="min-width:350px">&nbsp;</span></p>` : ''}
</div>

<div class="section">
<h2>Article VIII — Directors</h2>
<p>The initial Board of Directors shall consist of ${[a.board2, a.board3, a.board4, a.board5].filter(Boolean).length + 1} members. The names and addresses of the persons who are to serve as directors until the first annual meeting of members (or until their successors are elected and qualified) are those listed as incorporators in Article VII.</p>
</div>

<div class="section">
<h2>Article IX — Duration</h2>
<p>The duration of this corporation shall be perpetual.</p>
</div>

<div class="section">
<h2>Article X — Amendments</h2>
<p>These Articles of Incorporation may be amended in the manner authorized by law and by the Bylaws of this corporation.</p>
</div>

<p style="margin-top:3em">IN WITNESS WHEREOF, the undersigned, being the incorporator(s) of the above-named corporation, have executed these Articles of Incorporation this <span class="blank" style="min-width:40px">&nbsp;</span> day of <span class="blank" style="min-width:80px">&nbsp;</span>, 20<span class="blank" style="min-width:30px">&nbsp;</span>.</p>

<div style="margin-top:3em; display:flex; gap:4em; flex-wrap:wrap">
<div><div class="sig-line">Signature of Incorporator 1</div><p>${a.founderName || "[Founder Name]"}</p></div>
<div><div class="sig-line">Signature of Incorporator 2</div><p>${a.board2 || "[Board Member 2]"}</p></div>
</div>
` + docFooter;
}

// ── 2. BYLAWS ──
function generateBylaws(a, sd) {
  const orgName = a.orgName || "[Organization Name]";
  const stState = a.state || "[State]";
  const minBoard = sd ? sd.minBoardMembers : 3;

  return docHeader(`Bylaws of ${orgName}`, `A Nonprofit Corporation | State of ${stState}`) + `

<div class="section">
<h2>Article I — Name and Purpose</h2>
<h3>Section 1.1 — Name</h3>
<p>The name of this organization is <strong>${orgName}</strong> (the "Corporation").</p>
<h3>Section 1.2 — Purpose</h3>
<p>The Corporation is organized exclusively for charitable, educational, religious, and/or scientific purposes within the meaning of Section 501(c)(3) of the Internal Revenue Code. Specifically:</p>
<p><em>${a.activities || "[Insert specific purpose]"}</em></p>
<h3>Section 1.3 — Mission Statement</h3>
<p><em>${a.missionStatement || `The mission of ${orgName} is to ${a.problem ? 'address ' + a.problem.substring(0, 120) + '...' : '[insert mission]'}`}</em></p>
</div>

<div class="section">
<h2>Article II — Offices</h2>
<h3>Section 2.1 — Principal Office</h3>
<p>The principal office of the Corporation shall be located in ${stState}. The Corporation may have additional offices at such places as the Board of Directors may designate.</p>
</div>

<div class="section">
<h2>Article III — Board of Directors</h2>
<h3>Section 3.1 — General Powers</h3>
<p>The affairs of the Corporation shall be managed by its Board of Directors. The Board of Directors shall have control of and be responsible for the management of the affairs and property of the Corporation.</p>
<h3>Section 3.2 — Number, Tenure, and Qualifications</h3>
<p>The number of directors shall be not less than <strong>${minBoard}</strong> and may be increased by resolution of the Board. Directors shall serve two-year terms and may be reelected. Directors need not be residents of ${stState}.</p>
<h3>Section 3.3 — Initial Board of Directors</h3>
<p>The initial Board of Directors shall consist of:</p>
<ol>
<li>${a.founderName || "[Name]"} — Founder / President</li>
<li>${a.board2 || "[Board Member 2]"}</li>
<li>${a.board3 || "[Board Member 3]"}</li>
${a.board4 ? `<li>${a.board4}</li>` : ''}
${a.board5 ? `<li>${a.board5}</li>` : ''}
</ol>
<h3>Section 3.4 — Regular Meetings</h3>
<p>The Board of Directors shall hold at least four (4) regular meetings per year. The time and place of meetings shall be determined by the President or by resolution of the Board.</p>
<h3>Section 3.5 — Special Meetings</h3>
<p>Special meetings of the Board may be called by the President or by any two directors. Notice of special meetings shall be given at least five (5) days prior to the meeting.</p>
<h3>Section 3.6 — Quorum</h3>
<p>A majority of the directors then in office shall constitute a quorum for the transaction of business. The act of a majority of the directors present at a meeting at which a quorum is present shall be the act of the Board of Directors.</p>
<h3>Section 3.7 — Vacancies</h3>
<p>Any vacancy occurring on the Board of Directors may be filled by the affirmative vote of the majority of the remaining directors.</p>
<h3>Section 3.8 — Compensation</h3>
<p>Directors shall serve without compensation. Directors may be reimbursed for reasonable expenses incurred in the performance of their duties with approval of the Board.</p>
<h3>Section 3.9 — Removal</h3>
<p>Any director may be removed with or without cause by the vote of two-thirds (2/3) of the directors then in office at any regular or special meeting of the Board, provided that notice of such proposed removal was included in the notice of the meeting.</p>
</div>

<div class="section">
<h2>Article IV — Officers</h2>
<h3>Section 4.1 — Officers</h3>
<p>The officers of the Corporation shall be a President, a Vice President, a Secretary, and a Treasurer. The Board may elect or appoint such other officers as it deems necessary. One person may hold more than one office, except that the same person shall not serve as both President and Secretary.</p>
<h3>Section 4.2 — Duties of Officers</h3>
<p><strong>President:</strong> The President shall be the chief executive officer of the Corporation, shall preside at all meetings of the Board of Directors, shall have general and active management of the business of the Corporation, and shall see that all orders and resolutions of the Board are carried into effect.</p>
<p><strong>Vice President:</strong> The Vice President shall perform the duties of the President in the President's absence or disability.</p>
<p><strong>Secretary:</strong> The Secretary shall attend all meetings and record minutes, maintain records, provide notices, and perform such other duties as prescribed by the Board.</p>
<p><strong>Treasurer:</strong> The Treasurer shall have charge and custody of the Corporate funds, keep full and accurate accounts, and render financial statements to the Board as required.</p>
<h3>Section 4.3 — Term of Office</h3>
<p>Officers shall be elected annually by the Board and shall hold office for one (1) year unless removed sooner by the Board.</p>
</div>

<div class="section">
<h2>Article V — Committees</h2>
<h3>Section 5.1 — Standing Committees</h3>
<p>The Board may create standing committees including but not limited to: Executive, Finance, Fundraising, and Programs. Each committee shall have at least two (2) members.</p>
<h3>Section 5.2 — Committee Authority</h3>
<p>Committees shall not have the authority to amend the Articles of Incorporation, adopt a plan of merger, authorize the sale of assets, elect directors, amend the bylaws, or take any other action reserved to the Board by law or by these Bylaws.</p>
</div>

<div class="section">
<h2>Article VI — Finances</h2>
<h3>Section 6.1 — Fiscal Year</h3>
<p>The fiscal year of the Corporation shall begin on January 1 and end on December 31 of each year, unless changed by the Board.</p>
<h3>Section 6.2 — Budget</h3>
<p>The Treasurer shall prepare an annual budget for Board approval prior to the start of each fiscal year.</p>
<h3>Section 6.3 — Checks and Expenditures</h3>
<p>All checks or demands for money shall require the signature of the Treasurer and one other authorized officer. Expenditures over $<span class="blank" style="min-width:60px">&nbsp;</span> must be approved in advance by the Board.</p>
<h3>Section 6.4 — Audit</h3>
<p>The Board shall arrange for an annual review or audit of the Corporation's financial accounts as required by applicable law or as deemed necessary by the Board.</p>
</div>

<div class="section">
<h2>Article VII — Indemnification</h2>
<p>The Corporation shall indemnify its directors, officers, employees, and agents to the fullest extent permitted by the laws of the State of ${stState} and may advance expenses in connection with any proceeding upon receipt of an undertaking to repay such amount if indemnification is not ultimately authorized.</p>
</div>

<div class="section">
<h2>Article VIII — Amendments</h2>
<p>These Bylaws may be amended at any regular or special meeting of the Board of Directors by a two-thirds (2/3) vote of the directors then in office, provided that the amendment was included in the notice of the meeting.</p>
</div>

<div class="section">
<h2>Article IX — Parliamentary Authority</h2>
<p>The rules contained in the current edition of Robert's Rules of Order, Newly Revised, shall govern the Corporation in all cases to which they are applicable, and in which they are not inconsistent with these Bylaws and any special rules of order the Corporation may adopt.</p>
</div>

<div class="section">
<h2>Article X — Dissolution</h2>
<p>Upon dissolution of the Corporation, after paying or making provision for the payment of all liabilities, the Board shall distribute remaining assets exclusively to organizations exempt under Section 501(c)(3) of the Internal Revenue Code, as the Board shall determine.</p>
</div>

<p style="margin-top:3em">CERTIFIED that the foregoing constitutes the Bylaws of <strong>${orgName}</strong>, duly adopted by the Board of Directors.</p>
<p>Date: <span class="blank">&nbsp;</span> &nbsp;&nbsp; Location: <span class="blank">&nbsp;</span></p>

<div style="margin-top:3em; display:flex; gap:4em; flex-wrap:wrap">
<div><div class="sig-line">President</div><p>${a.founderName || "[President Name]"}</p></div>
<div><div class="sig-line">Secretary</div><p>${a.board2 || "[Secretary Name]"}</p></div>
</div>
` + docFooter;
}

// ── 3. CONFLICT OF INTEREST POLICY ──
function generateConflictPolicy(a) {
  const orgName = a.orgName || "[Organization Name]";
  return docHeader(`Conflict of Interest Policy`, `${orgName} | Required for IRS Form 1023`) + `

<div class="section">
<p>This Conflict of Interest Policy is adopted to protect the interests of <strong>${orgName}</strong> (the "Corporation") when it is contemplating entering into a transaction or arrangement that might benefit the private interests of an officer or director of the Corporation or might result in a possible excess benefit transaction.</p>
</div>

<div class="section">
<h2>Article I — Definitions</h2>
<h3>Section 1 — Interested Person</h3>
<p>Any director, principal officer, or member of a committee with governing board delegated powers, who has a direct or indirect financial interest, as defined below, is an interested person.</p>
<h3>Section 2 — Financial Interest</h3>
<p>A person has a financial interest if the person has, directly or indirectly, through business, investment, or family: (a) an ownership or investment interest in any entity with which the Corporation has a transaction or arrangement; (b) a compensation arrangement with the Corporation or with any entity or individual with which the Corporation has a transaction or arrangement; or (c) a potential ownership or investment interest in, or compensation arrangement with, any entity or individual with which the Corporation is negotiating a transaction or arrangement.</p>
</div>

<div class="section">
<h2>Article II — Procedures</h2>
<h3>Section 1 — Duty to Disclose</h3>
<p>In connection with any actual or possible conflict of interest, an interested person must disclose the existence of the financial interest and be given the opportunity to disclose all material facts to the directors and members of committees with governing board delegated powers considering the proposed transaction or arrangement.</p>
<h3>Section 2 — Determining Whether a Conflict of Interest Exists</h3>
<p>After disclosure of the financial interest and all material facts, and after any discussion with the interested person, the interested person shall leave the governing board or committee meeting while the determination of whether a conflict of interest exists is discussed and voted upon. The remaining board or committee members shall decide if a conflict of interest exists.</p>
<h3>Section 3 — Procedures for Addressing the Conflict of Interest</h3>
<p>An interested person may make a presentation at the governing board or committee meeting, but after the presentation, the interested person shall leave the meeting during the discussion of, and the vote on, the transaction or arrangement involving the possible conflict of interest. The chairperson of the governing board or committee shall, if appropriate, appoint a disinterested person or committee to investigate alternatives to the proposed transaction or arrangement.</p>
</div>

<div class="section">
<h2>Article III — Records of Proceedings</h2>
<p>The minutes of the governing board and all committees with board delegated powers shall contain: (a) the names of persons who disclosed or otherwise were found to have a financial interest in connection with an actual or possible conflict of interest; (b) the nature of the financial interest; (c) any action taken to determine whether a conflict of interest was present; and (d) the governing board's or committee's decision as to whether a conflict of interest in fact existed.</p>
</div>

<div class="section">
<h2>Article IV — Compensation</h2>
<p>A voting member of any committee whose jurisdiction includes compensation matters and who receives compensation, directly or indirectly, from the Corporation for services is precluded from voting on matters pertaining to that member's compensation.</p>
</div>

<div class="section">
<h2>Article V — Annual Statements</h2>
<p>Each director, principal officer, and member of a committee with governing board delegated powers shall annually sign a statement which affirms such person: (a) has received a copy of the conflicts of interest policy; (b) has read and understands the policy; (c) has agreed to comply with the policy; and (d) understands the Corporation is charitable and in order to maintain its federal tax exemption it must engage primarily in activities which accomplish one or more of its tax-exempt purposes.</p>
</div>

<div class="section">
<h2>Article VI — Periodic Reviews</h2>
<p>To ensure the Corporation operates in a manner consistent with charitable purposes and does not engage in activities that could jeopardize its tax-exempt status, periodic reviews shall be conducted. The periodic reviews shall, at a minimum, include the following subjects: (a) whether compensation arrangements and benefits are reasonable, based on competent survey information, and the result of arm's length bargaining; and (b) whether partnerships, joint ventures, and arrangements with management organizations conform to the Corporation's written policies, are properly recorded, reflect reasonable investment or payments for goods and services, further charitable purposes and do not result in inurement, impermissible private benefit or in an excess benefit transaction.</p>
</div>

<p style="margin-top:3em"><strong>Annual Certification — To be signed by each director each year:</strong></p>
<p>I, the undersigned, a director/officer of <strong>${orgName}</strong>, acknowledge that I have received, read, and understand the Conflict of Interest Policy of this Corporation, and I agree to comply with it.</p>

<table style="width:100%; border-collapse:collapse; margin-top:1em">
<tr style="border-bottom:1px solid #ccc"><td style="padding:8px 0"><strong>Name</strong></td><td><strong>Role</strong></td><td><strong>Signature</strong></td><td><strong>Date</strong></td></tr>
${[
  { name: a.founderName, role: 'President/Founder' },
  { name: a.board2, role: 'Director' },
  { name: a.board3, role: 'Director' },
  { name: a.board4, role: 'Director' },
  { name: a.board5, role: 'Director' },
].filter(r => r.name).map(r => `<tr style="border-bottom:1px solid #eee"><td style="padding:8px 0">${r.name}</td><td>${r.role}</td><td>&nbsp;</td><td>&nbsp;</td></tr>`).join('')}
</table>
` + docFooter;
}

// ── 4. FIRST BOARD MEETING MINUTES ──
function generateBoardMinutes(a, sd) {
  const orgName = a.orgName || "[Organization Name]";
  const stState = a.state || "[State]";
  return docHeader(`Minutes of the Organizational Meeting of the Board of Directors`, `${orgName}`) + `

<div class="section">
<p><strong>Date:</strong> <span class="blank">&nbsp;</span> &nbsp;&nbsp; <strong>Time:</strong> <span class="blank">&nbsp;</span> &nbsp;&nbsp; <strong>Location:</strong> <span class="blank" style="min-width:220px">&nbsp;</span></p>
<p><strong>Directors Present:</strong></p>
<ol>
<li>${a.founderName || "[Name]"} (Presiding)</li>
<li>${a.board2 || "[Name]"}</li>
<li>${a.board3 || "[Name]"}</li>
${a.board4 ? `<li>${a.board4}</li>` : ''}
${a.board5 ? `<li>${a.board5}</li>` : ''}
</ol>
<p><strong>Quorum:</strong> A quorum of the Board of Directors being present, the meeting was called to order by ${a.founderName || "[Founder Name]"}.</p>
</div>

<div class="section">
<h2>I. Formation of the Corporation</h2>
<p>The Secretary presented the Articles of Incorporation of <strong>${orgName}</strong>, filed with the ${stState} Secretary of State. The Articles were accepted and a copy was ordered placed in the corporate records.</p>
</div>

<div class="section">
<h2>II. Adoption of Bylaws</h2>
<p>The Bylaws of the Corporation were presented and discussed. Upon motion duly made and seconded, the Bylaws were unanimously adopted by the Board of Directors.</p>
<p><strong>Vote:</strong> Ayes: <span class="blank" style="min-width:40px">&nbsp;</span> &nbsp; Nays: <span class="blank" style="min-width:40px">&nbsp;</span> &nbsp; Abstentions: <span class="blank" style="min-width:40px">&nbsp;</span></p>
</div>

<div class="section">
<h2>III. Election of Officers</h2>
<p>The following officers were elected to serve until the next annual meeting or until their successors are duly elected and qualified:</p>
<table style="width:100%; border-collapse:collapse; margin-top:0.5em">
<tr style="border-bottom:1px solid #ccc"><td style="padding:6px 0"><strong>Office</strong></td><td><strong>Name</strong></td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:6px 0">President</td><td>${a.founderName || "[Name]"}</td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:6px 0">Vice President</td><td>${a.board2 || "[Name]"}</td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:6px 0">Secretary</td><td>${a.board3 || "[Name]"}</td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:6px 0">Treasurer</td><td>${a.board4 || a.board2 || "[Name]"}</td></tr>
</table>
<p style="margin-top:0.75em"><strong>Vote:</strong> Ayes: <span class="blank" style="min-width:40px">&nbsp;</span> &nbsp; Nays: <span class="blank" style="min-width:40px">&nbsp;</span> &nbsp; Abstentions: <span class="blank" style="min-width:40px">&nbsp;</span></p>
</div>

<div class="section">
<h2>IV. Mission and Purpose</h2>
<p>The Board discussed the mission and purpose of the Corporation:</p>
<p><em>"${a.activities || "[Mission and activities description]"}"</em></p>
<p>The Board confirmed that the Corporation's activities will serve: <em>${a.whoHelp || "[Who you serve]"}</em></p>
</div>

<div class="section">
<h2>V. Adoption of Conflict of Interest Policy</h2>
<p>The Conflict of Interest Policy was presented and discussed. Upon motion duly made and seconded, the policy was unanimously adopted. Each director present acknowledged receipt of the policy.</p>
<p><strong>Vote:</strong> Ayes: <span class="blank" style="min-width:40px">&nbsp;</span> &nbsp; Nays: <span class="blank" style="min-width:40px">&nbsp;</span></p>
</div>

<div class="section">
<h2>VI. Banking Resolution</h2>
<p>Upon motion duly made and seconded, the Board resolved to open a bank account in the name of <strong>${orgName}</strong>. The Treasurer was authorized to open such account and shall require dual signatures for withdrawals over $<span class="blank" style="min-width:60px">&nbsp;</span>.</p>
<p><strong>Vote:</strong> Ayes: <span class="blank" style="min-width:40px">&nbsp;</span> &nbsp; Nays: <span class="blank" style="min-width:40px">&nbsp;</span></p>
</div>

<div class="section">
<h2>VII. Application for EIN</h2>
<p>The Board authorized the filing of Form SS-4 (or online application) with the Internal Revenue Service to obtain an Employer Identification Number (EIN) for the Corporation.</p>
</div>

<div class="section">
<h2>VIII. Application for 501(c)(3) Status</h2>
<p>The Board authorized the filing of IRS Form 1023 (or Form 1023-EZ, if eligible) to apply for recognition of tax-exempt status under Section 501(c)(3) of the Internal Revenue Code.</p>
</div>

<div class="section">
<h2>IX. Next Meeting</h2>
<p>The next regular meeting of the Board shall be held on: <span class="blank" style="min-width:180px">&nbsp;</span></p>
</div>

<div class="section">
<h2>X. Adjournment</h2>
<p>There being no further business to come before the meeting, the meeting was adjourned.</p>
</div>

<p style="margin-top:3em">Respectfully submitted,</p>
<div style="margin-top:2em; display:flex; gap:4em; flex-wrap:wrap">
<div><div class="sig-line">Secretary, Board of Directors</div><p>${a.board3 || "[Secretary Name]"}</p></div>
<div><div class="sig-line">President, Board of Directors</div><p>${a.founderName || "[President Name]"}</p></div>
</div>
` + docFooter;
}

// ── 5. MISSION STATEMENT WORKSHEET ──
function generateMissionStatement(a) {
  return docHeader("Mission Statement Worksheet", `${a.orgName || "Your Nonprofit"} | For Internal Use &amp; IRS Filing`) + `
<div class="section">
<h2>Your Draft Mission Statement</h2>
<p>The following was drafted based on your intake form answers. Review and refine it — your mission statement should be 1–3 sentences that clearly explain what you do, who you serve, and why it matters.</p>
<div style="background:#f0f8f4; border-left:4px solid #2d8f6f; padding:1em 1.25em; margin:1em 0; font-size:13pt; font-style:italic; line-height:1.7;">
"The mission of <strong>${a.orgName || "[Organization Name]"}</strong> is to ${a.activities ? a.activities.substring(0, 200) : '[describe your activities]'} in order to serve ${a.whoHelp ? a.whoHelp.substring(0, 150) : '[who you serve]'} in ${a.location || '[your location]'}."
</div>
</div>
<div class="section">
<h2>Mission Statement Checklist</h2>
<p>A strong mission statement should answer all of these questions:</p>
<table style="width:100%; border-collapse:collapse">
<tr style="border-bottom:1px solid #ccc"><td style="padding:8px 0"><input type="checkbox"> Does it say <strong>WHAT</strong> you do?</td></tr>
<tr style="border-bottom:1px solid #ccc"><td style="padding:8px 0"><input type="checkbox"> Does it say <strong>WHO</strong> you serve?</td></tr>
<tr style="border-bottom:1px solid #ccc"><td style="padding:8px 0"><input type="checkbox"> Does it say <strong>WHY</strong> you do it (the impact)?</td></tr>
<tr style="border-bottom:1px solid #ccc"><td style="padding:8px 0"><input type="checkbox"> Is it short enough to memorize? (Under 2 sentences ideally)</td></tr>
<tr style="border-bottom:1px solid #ccc"><td style="padding:8px 0"><input type="checkbox"> Is it written in plain language that anyone can understand?</td></tr>
<tr><td style="padding:8px 0"><input type="checkbox"> Does it avoid jargon or vague buzzwords?</td></tr>
</table>
</div>
<div class="section">
<h2>Your Notes / Revisions</h2>
<p>Use this space to write your revised mission statement:</p>
<div style="border:1px solid #ccc; min-height:120px; margin:1em 0; padding:1em;">&nbsp;</div>
</div>
<div class="section">
<h2>Problem You Are Solving</h2>
<p><em>${a.problem || "[Describe the problem your nonprofit addresses]"}</em></p>
</div>
<div class="section">
<h2>How You Will Help</h2>
<p><em>${a.activities || "[Describe your programs and activities]"}</em></p>
</div>
` + docFooter;
}

// ── 6. EIN APPLICATION CHECKLIST ──
function generateEINChecklist(a, sd) {
  return docHeader("EIN Application Checklist", `${a.orgName || "Your Nonprofit"} | Apply Free at IRS.gov`) + `
<div class="section">
<p>An EIN (Employer Identification Number) is a free, 9-digit tax ID number from the IRS. You need it before opening a bank account or applying for 501(c)(3) status. You can apply in minutes online.</p>
<h2>How to Apply for Your EIN</h2>
<p><strong>Option 1 (Recommended): Apply Online</strong><br>Go to <strong>https://www.irs.gov/businesses/small-businesses-self-employed/apply-for-an-employer-identification-number-ein-online</strong><br>The online tool is available Monday–Friday, 7am–10pm ET. You'll receive your EIN immediately.</p>
<p><strong>Option 2: Mail or Fax Form SS-4</strong><br>Download Form SS-4 from IRS.gov and mail or fax it. Processing takes 4–6 weeks by mail, 4 business days by fax.</p>
</div>
<div class="section">
<h2>What You'll Need to Apply</h2>
<table style="width:100%; border-collapse:collapse">
<tr style="border-bottom:1px solid #ccc"><td style="padding:8px 0; width:60%"><strong>Item</strong></td><td><strong>Your Information</strong></td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:8px 0">Legal name of organization</td><td>${a.orgName || "[Your org name]"}</td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:8px 0">Responsible party name</td><td>${a.founderName || "[Your name]"}</td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:8px 0">Responsible party SSN or ITIN</td><td>Your personal SSN (required)</td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:8px 0">Mailing address</td><td><span class="blank" style="min-width:200px">&nbsp;</span></td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:8px 0">State of formation</td><td>${a.state || "[Your state]"}</td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:8px 0">Date organization was formed</td><td><span class="blank">&nbsp;</span></td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:8px 0">Reason for applying</td><td>Started new organization</td></tr>
<tr><td style="padding:8px 0">Entity type</td><td>Other nonprofit / tax-exempt organization</td></tr>
</table>
</div>
<div class="section">
<h2>Checklist — Before You Apply</h2>
<table style="width:100%; border-collapse:collapse">
<tr style="border-bottom:1px solid #eee"><td style="padding:8px 0"><input type="checkbox"> Articles of Incorporation are signed and filed with ${a.state || "your state"}</td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:8px 0"><input type="checkbox"> You have your state-issued confirmation/receipt</td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:8px 0"><input type="checkbox"> You have a valid SSN or ITIN as the responsible party</td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:8px 0"><input type="checkbox"> You know the exact legal name of your organization</td></tr>
<tr><td style="padding:8px 0"><input type="checkbox"> You have the mailing address for the organization</td></tr>
</table>
</div>
<div class="section">
<h2>After You Receive Your EIN</h2>
<table style="width:100%; border-collapse:collapse">
<tr style="border-bottom:1px solid #eee"><td style="padding:8px 0"><input type="checkbox"> Save your EIN confirmation letter (CP 575)</td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:8px 0"><input type="checkbox"> Open a bank account using the EIN</td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:8px 0"><input type="checkbox"> Write down your EIN: <span class="blank" style="min-width:140px">&nbsp;</span></td></tr>
<tr><td style="padding:8px 0"><input type="checkbox"> Begin preparing IRS Form 1023 or 1023-EZ</td></tr>
</table>
</div>
` + docFooter;
}

// ── 7. IRS FORM 1023 PREP GUIDE ──
function generateIRSPrep(a, sd) {
  const totalRevenue = a.budget ? a.budget : "unknown";
  const use1023EZ = a.budgetAmount && parseInt(a.budgetAmount) < 50000;
  return docHeader("IRS Form 1023 Preparation Guide", `${a.orgName || "Your Nonprofit"} | Apply for 501(c)(3) Tax-Exempt Status`) + `
<div class="section">
<h2>Which Form Do You Need?</h2>
<table style="width:100%; border-collapse:collapse; margin-bottom:1em">
<tr style="background:#f5f5f5"><td style="padding:10px; border:1px solid #ddd"><strong>Form 1023-EZ (Short Form)</strong></td><td style="padding:10px; border:1px solid #ddd"><strong>Form 1023 (Full Form)</strong></td></tr>
<tr><td style="padding:10px; border:1px solid #ddd">Filing fee: <strong>$275</strong></td><td style="padding:10px; border:1px solid #ddd">Filing fee: <strong>$600</strong></td></tr>
<tr><td style="padding:10px; border:1px solid #ddd">Projected annual gross receipts under $50,000</td><td style="padding:10px; border:1px solid #ddd">Projected annual gross receipts over $50,000</td></tr>
<tr><td style="padding:10px; border:1px solid #ddd">Total assets under $250,000</td><td style="padding:10px; border:1px solid #ddd">Total assets over $250,000</td></tr>
<tr><td style="padding:10px; border:1px solid #ddd">Simpler to complete</td><td style="padding:10px; border:1px solid #ddd">More detailed — covers your programs in depth</td></tr>
<tr><td style="padding:10px; border:1px solid #ddd">Filed entirely online at pay.gov</td><td style="padding:10px; border:1px solid #ddd">Filed online at pay.gov</td></tr>
</table>
<p><strong>Note:</strong> Some organization types CANNOT use Form 1023-EZ, including churches, schools, hospitals, and supporting organizations.</p>
</div>

<div class="section">
<h2>Information You Will Need for the Application</h2>
<h3>Part I — Identification</h3>
<table style="width:100%; border-collapse:collapse">
<tr style="border-bottom:1px solid #eee"><td style="padding:7px 0; width:55%">Legal name of organization</td><td>${a.orgName || "[Name]"}</td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:7px 0">EIN</td><td>Obtain before filing (see EIN checklist)</td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:7px 0">Mailing address</td><td><span class="blank" style="min-width:200px">&nbsp;</span></td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:7px 0">Month tax year ends</td><td>December (recommended)</td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:7px 0">Date incorporated</td><td><span class="blank">&nbsp;</span></td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:7px 0">State of formation</td><td>${a.state || "[State]"}</td></tr>
<tr><td style="padding:7px 0">Contact person</td><td>${a.founderName || "[Name]"} — ${a.founderEmail || "[Email]"}</td></tr>
</table>

<h3>Part II — Organizational Structure</h3>
<table style="width:100%; border-collapse:collapse">
<tr style="border-bottom:1px solid #eee"><td style="padding:7px 0; width:55%">Type of entity</td><td>Nonprofit Corporation</td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:7px 0">Copy of Articles of Incorporation</td><td>Must be attached</td></tr>
<tr><td style="padding:7px 0">Copy of Bylaws</td><td>Must be attached</td></tr>
</table>

<h3>Part IV — Narrative Description of Activities (Most Important!)</h3>
<p>The IRS will ask you to describe your programs. Use plain language. Below is a draft based on your answers:</p>
<div style="background:#f9f9f9; border:1px solid #ddd; padding:1em; margin:0.5em 0">
<p><strong>Program 1: ${a.orgName || "[Program Name]"}</strong></p>
<p><em>Description:</em> ${a.activities || "[Describe your programs in detail]"}</p>
<p><em>Who is served:</em> ${a.whoHelp || "[Who you serve]"}</p>
<p><em>Geographic area:</em> ${a.location || "[Location]"}</p>
<p><em>How funded:</em> ${a.fundingSources ? a.fundingSources.join(', ') : "[Describe funding sources]"}</p>
</div>

<h3>Part V — Compensation and Other Financial Arrangements</h3>
<p>You will need to list all officers, directors, and highly compensated employees and their compensation. If starting out with all volunteers, state that.</p>

<h3>Part IX — Financial Data</h3>
<p>Projected budget for first 3 years:</p>
<table style="width:100%; border-collapse:collapse">
<tr style="background:#f5f5f5; border-bottom:1px solid #ddd"><td style="padding:8px"><strong>Revenue Source</strong></td><td style="padding:8px"><strong>Year 1</strong></td><td style="padding:8px"><strong>Year 2</strong></td><td style="padding:8px"><strong>Year 3</strong></td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:8px">Donations</td><td style="padding:8px"><span class="blank">&nbsp;</span></td><td style="padding:8px"><span class="blank">&nbsp;</span></td><td style="padding:8px"><span class="blank">&nbsp;</span></td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:8px">Grants</td><td style="padding:8px"><span class="blank">&nbsp;</span></td><td style="padding:8px"><span class="blank">&nbsp;</span></td><td style="padding:8px"><span class="blank">&nbsp;</span></td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:8px">Events</td><td style="padding:8px"><span class="blank">&nbsp;</span></td><td style="padding:8px"><span class="blank">&nbsp;</span></td><td style="padding:8px"><span class="blank">&nbsp;</span></td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:8px">Program Fees</td><td style="padding:8px"><span class="blank">&nbsp;</span></td><td style="padding:8px"><span class="blank">&nbsp;</span></td><td style="padding:8px"><span class="blank">&nbsp;</span></td></tr>
<tr style="background:#f0f8f4"><td style="padding:8px"><strong>TOTAL Revenue</strong></td><td style="padding:8px">${a.budget || "<span class='blank'>&nbsp;</span>"}</td><td style="padding:8px"><span class="blank">&nbsp;</span></td><td style="padding:8px"><span class="blank">&nbsp;</span></td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:8px">Total Expenses</td><td style="padding:8px"><span class="blank">&nbsp;</span></td><td style="padding:8px"><span class="blank">&nbsp;</span></td><td style="padding:8px"><span class="blank">&nbsp;</span></td></tr>
</table>
</div>

<div class="section">
<h2>Documents to Attach to Form 1023</h2>
<table style="width:100%; border-collapse:collapse">
<tr style="border-bottom:1px solid #eee"><td style="padding:8px 0"><input type="checkbox"> Signed Articles of Incorporation (with state filing stamp)</td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:8px 0"><input type="checkbox"> Bylaws (signed)</td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:8px 0"><input type="checkbox"> Conflict of Interest Policy (signed)</td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:8px 0"><input type="checkbox"> First Board Meeting Minutes</td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:8px 0"><input type="checkbox"> EIN Confirmation Letter</td></tr>
<tr><td style="padding:8px 0"><input type="checkbox"> Financial projections for 3 years</td></tr>
</table>
</div>

<div class="section">
<h2>Where to File</h2>
<p>File online at <strong>https://www.pay.gov</strong> — search for "Form 1023" or "Form 1023-EZ".</p>
<p>The IRS typically responds in <strong>3–6 months</strong>. You can operate as a nonprofit while waiting, but you don't have official tax-exempt status yet.</p>
</div>
` + docFooter;
}

// ── 8. STATE-SPECIFIC CHECKLIST ──
function generateStateChecklist(a, sd) {
  if (!sd) return docHeader("State Filing Checklist", "Select your state to see state-specific requirements") + "<p>State not found.</p>" + docFooter;
  const orgName = a.orgName || "[Organization Name]";
  const unique = sd.unique || [];
  return docHeader(`${sd.name} Nonprofit Filing Checklist`, `${orgName} | ${sd.name}-Specific Requirements`) + `
<div class="section">
<h2>Your State: ${sd.name}</h2>
<table style="width:100%; border-collapse:collapse; margin-bottom:1em">
<tr style="border-bottom:1px solid #eee"><td style="padding:8px 0; width:55%">Formation document</td><td><strong>${sd.form}</strong></td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:8px 0">Filing agency</td><td><a href="${sd.agencyUrl}" style="color:#2d8f6f">${sd.agency}</a></td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:8px 0">State filing fee</td><td><strong>$${sd.fee}</strong></td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:8px 0">Processing time</td><td>${sd.processingDays} business days</td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:8px 0">Minimum board members</td><td>${sd.minBoardMembers}</td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:8px 0">Charitable solicitation registration</td><td>${sd.solicitationReg ? `Required — Fee: $${sd.solicitationFee || 'Free'}` : 'Not required'}</td></tr>
<tr><td style="padding:8px 0">State income tax exemption</td><td>${sd.incomeTaxExempt ? 'Available — apply separately' : 'N/A'}</td></tr>
</table>
</div>

<div class="section">
<h2>State-Specific Notes for ${sd.name}</h2>
<p>${sd.notes}</p>
${unique.length > 0 ? `<h3>Unique Requirements / Watch Out For:</h3><ul>${unique.map(u => `<li>${u}</li>`).join('')}</ul>` : ''}
</div>

<div class="section">
<h2>${sd.name} Step-by-Step Checklist</h2>
<table style="width:100%; border-collapse:collapse">
<tr style="border-bottom:1px solid #eee"><td style="padding:9px 0"><input type="checkbox"> Choose and verify your nonprofit name is available in ${sd.name}</td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:9px 0"><input type="checkbox"> Recruit at least ${sd.minBoardMembers} board members</td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:9px 0"><input type="checkbox"> Identify a registered agent in ${sd.name}</td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:9px 0"><input type="checkbox"> Prepare and sign your ${sd.form}</td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:9px 0"><input type="checkbox"> File ${sd.form} with the ${sd.agency} — Fee: $${sd.fee}</td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:9px 0"><input type="checkbox"> Receive confirmation from the state (est. ${sd.processingDays} days)</td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:9px 0"><input type="checkbox"> Apply for EIN from IRS (free, at IRS.gov)</td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:9px 0"><input type="checkbox"> Hold first board meeting and adopt bylaws</td></tr>
${sd.solicitationReg ? `<tr style="border-bottom:1px solid #eee"><td style="padding:9px 0"><input type="checkbox"> Register for charitable solicitation in ${sd.name} — Fee: $${sd.solicitationFee || 0}</td></tr>` : ''}
<tr style="border-bottom:1px solid #eee"><td style="padding:9px 0"><input type="checkbox"> File IRS Form 1023 or 1023-EZ for federal 501(c)(3) status</td></tr>
${sd.incomeTaxExempt ? `<tr style="border-bottom:1px solid #eee"><td style="padding:9px 0"><input type="checkbox"> Apply for ${sd.name} state tax exemption (after receiving IRS approval)</td></tr>` : ''}
<tr style="border-bottom:1px solid #eee"><td style="padding:9px 0"><input type="checkbox"> Open a bank account in the nonprofit's name</td></tr>
<tr><td style="padding:9px 0"><input type="checkbox"> Set up annual reporting reminders for ${sd.name}</td></tr>
</table>
</div>

<div class="section">
<h2>Total Estimated State Costs</h2>
<table style="width:100%; border-collapse:collapse">
<tr style="border-bottom:1px solid #eee"><td style="padding:8px 0">State incorporation fee</td><td>$${sd.fee}</td></tr>
${sd.solicitationReg ? `<tr style="border-bottom:1px solid #eee"><td style="padding:8px 0">Charitable solicitation registration</td><td>$${sd.solicitationFee || 0}</td></tr>` : ''}
<tr style="border-bottom:1px solid #eee"><td style="padding:8px 0">IRS filing fee (1023-EZ)</td><td>$275</td></tr>
<tr style="border-bottom:1px solid #eee"><td style="padding:8px 0">IRS filing fee (1023 full)</td><td>$600</td></tr>
<tr style="background:#f0f8f4"><td style="padding:8px 0"><strong>Estimated minimum total (1023-EZ)</strong></td><td><strong>$${sd.fee + (sd.solicitationFee || 0) + 275}</strong></td></tr>
</table>
</div>
` + docFooter;
}
