// ── Yearly Document Generators for Start Your Cause ──
// Generates annual filing and compliance documents

function generateYearlyDocs(answers, stateData, year) {
  return {
    form990:        generateForm990Prep(answers, stateData, year),
    stateReport:    generateStateAnnualReport(answers, stateData, year),
    annualMinutes:  generateAnnualMinutes(answers, stateData, year),
    donorLetters:   generateDonorLetters(answers, year),
  };
}

function ydocHeader(title, subtitle) {
  return `<!DOCTYPE html><html><head><meta charset="UTF-8">
<title>${title}</title>
<style>
  body{font-family:'Times New Roman',Times,serif;max-width:750px;margin:40px auto;padding:0 2rem 4rem;color:#1a1a1a;font-size:12pt;line-height:1.7}
  h1{text-align:center;font-size:16pt;margin-bottom:4px;text-transform:uppercase;letter-spacing:1px}
  h2{font-size:13pt;margin-top:2em;margin-bottom:4px;text-transform:uppercase;border-bottom:1px solid #ccc;padding-bottom:4px}
  h3{font-size:12pt;margin-top:1.5em;margin-bottom:4px}
  .center{text-align:center}
  .blank{display:inline-block;min-width:180px;border-bottom:1px solid #000}
  .sig-line{margin-top:3em;border-top:1px solid #000;width:280px;padding-top:4px;font-size:11pt}
  .notice{background:#fffbe6;border:1px solid #e0c84a;padding:12px 16px;font-size:11pt;margin-bottom:1.5em;border-radius:4px;font-family:Arial,sans-serif}
  .print-btn{font-family:Arial;background:#2d8f6f;color:#fff;border:none;padding:10px 24px;border-radius:6px;font-size:13px;cursor:pointer;margin-bottom:24px}
  .info-box{background:#f0f8f4;border-left:4px solid #2d8f6f;padding:1em 1.25em;margin:1em 0;font-size:11pt}
  .warn-box{background:#fffbe6;border-left:4px solid #e0c84a;padding:1em 1.25em;margin:1em 0;font-size:11pt}
  .err-box{background:#fff0f0;border-left:4px solid #e05555;padding:1em 1.25em;margin:1em 0;font-size:11pt}
  table{width:100%;border-collapse:collapse;margin:1em 0}
  td,th{padding:7px 8px;border:1px solid #ddd;font-size:11pt;vertical-align:top}
  th{background:#f5f5f5;font-weight:bold;text-align:left}
  .no-border td{border:none;padding:6px 0}
  @media print{.print-btn,.notice{display:none}}
  p{margin:0 0 0.75em}
  ol,ul{margin-left:1.5em}
  li{margin-bottom:.4em}
  input[type=checkbox]{margin-right:6px}
</style></head><body>
<button class="print-btn" onclick="window.print()">🖨 Print / Save as PDF</button>
<div class="notice">⚠️ <strong>Important:</strong> These documents are templates generated by Start Your Cause. They are NOT a substitute for legal or tax advice. Have a licensed attorney or CPA review all filings. IRS forms and state requirements change annually — always verify current requirements at IRS.gov and your state agency.</div>
<h1>${title}</h1>
<p class="center" style="margin-bottom:2em">${subtitle}</p>`;
}
const ydocFooter = `</body></html>`;

// ─────────────────────────────────────────────
// 1. FORM 990 PREP GUIDE
// ─────────────────────────────────────────────
function generateForm990Prep(a, sd, year) {
  const orgName = a.orgName || "[Organization Name]";
  const taxYear = year || new Date().getFullYear() - 1;
  const dueDate = `May 15, ${parseInt(taxYear)+1}`;

  return ydocHeader(
    `IRS Form 990 Preparation Guide`,
    `${orgName} | Tax Year ${taxYear} | Due: ${dueDate}`
  ) + `

<div class="info-box">
<strong>Which form do you need?</strong><br>
• <strong>Form 990-N</strong> ("e-Postcard") — Gross receipts normally ≤ $50,000. Filed online only. No financial detail required.<br>
• <strong>Form 990-EZ</strong> — Gross receipts &lt; $200,000 AND total assets &lt; $500,000.<br>
• <strong>Form 990</strong> (full) — Gross receipts ≥ $200,000 OR total assets ≥ $500,000.<br>
• <strong>Private foundations</strong> always file Form 990-PF regardless of size.
</div>

<h2>Part I — Summary</h2>
<table>
<tr><th>Item</th><th>Your Information</th></tr>
<tr><td>Organization name</td><td>${orgName}</td></tr>
<tr><td>EIN</td><td><span class="blank">&nbsp;</span></td></tr>
<tr><td>Tax year</td><td>January 1 – December 31, ${taxYear}</td></tr>
<tr><td>Address</td><td>${a.address||'<span class="blank">&nbsp;</span>'}</td></tr>
<tr><td>State of formation</td><td>${sd?sd.name:(a.state||'<span class="blank">&nbsp;</span>')}</td></tr>
<tr><td>Website</td><td>https://startyourcause.org</td></tr>
<tr><td>Mission statement</td><td>${a.missionStatement||a.activities||'<span class="blank" style="min-width:350px">&nbsp;</span>'}</td></tr>
<tr><td>Number of voting board members</td><td>${[a.founderName,a.board2,a.board3,a.board4,a.board5].filter(Boolean).length}</td></tr>
<tr><td>Number of employees</td><td><span class="blank" style="min-width:60px">&nbsp;</span></td></tr>
<tr><td>Number of volunteers</td><td><span class="blank" style="min-width:60px">&nbsp;</span></td></tr>
</table>

<h2>Part II — Revenue (Fill in actuals for ${taxYear})</h2>
<table>
<tr><th>Revenue Source</th><th>Amount</th></tr>
<tr><td>Contributions and grants</td><td>$<span class="blank" style="min-width:100px">&nbsp;</span></td></tr>
<tr><td>Program service revenue</td><td>$<span class="blank" style="min-width:100px">&nbsp;</span></td></tr>
<tr><td>Investment income</td><td>$<span class="blank" style="min-width:100px">&nbsp;</span></td></tr>
<tr><td>Fundraising events (gross)</td><td>$<span class="blank" style="min-width:100px">&nbsp;</span></td></tr>
<tr><td>Other revenue</td><td>$<span class="blank" style="min-width:100px">&nbsp;</span></td></tr>
<tr><th>TOTAL REVENUE</th><th>$<span class="blank" style="min-width:100px">&nbsp;</span></th></tr>
</table>

<h2>Part III — Expenses (Fill in actuals for ${taxYear})</h2>
<table>
<tr><th>Expense Category</th><th>Total</th><th>Program</th><th>Management</th><th>Fundraising</th></tr>
<tr><td>Grants and similar amounts paid</td><td>$<span class="blank">&nbsp;</span></td><td></td><td></td><td></td></tr>
<tr><td>Salaries and wages</td><td>$<span class="blank">&nbsp;</span></td><td></td><td></td><td></td></tr>
<tr><td>Professional fees</td><td>$<span class="blank">&nbsp;</span></td><td></td><td></td><td></td></tr>
<tr><td>Occupancy (rent, utilities)</td><td>$<span class="blank">&nbsp;</span></td><td></td><td></td><td></td></tr>
<tr><td>Travel</td><td>$<span class="blank">&nbsp;</span></td><td></td><td></td><td></td></tr>
<tr><td>Supplies and materials</td><td>$<span class="blank">&nbsp;</span></td><td></td><td></td><td></td></tr>
<tr><td>Marketing and communications</td><td>$<span class="blank">&nbsp;</span></td><td></td><td></td><td></td></tr>
<tr><td>Technology and software</td><td>$<span class="blank">&nbsp;</span></td><td></td><td></td><td></td></tr>
<tr><td>Other expenses</td><td>$<span class="blank">&nbsp;</span></td><td></td><td></td><td></td></tr>
<tr><th>TOTAL EXPENSES</th><th>$<span class="blank">&nbsp;</span></th><th></th><th></th><th></th></tr>
</table>

<h2>Part IV — Balance Sheet</h2>
<table>
<tr><th>Assets</th><th>Beginning of Year</th><th>End of Year</th></tr>
<tr><td>Cash and cash equivalents</td><td>$<span class="blank">&nbsp;</span></td><td>$<span class="blank">&nbsp;</span></td></tr>
<tr><td>Savings and temporary investments</td><td>$<span class="blank">&nbsp;</span></td><td>$<span class="blank">&nbsp;</span></td></tr>
<tr><td>Accounts receivable</td><td>$<span class="blank">&nbsp;</span></td><td>$<span class="blank">&nbsp;</span></td></tr>
<tr><td>Equipment (net of depreciation)</td><td>$<span class="blank">&nbsp;</span></td><td>$<span class="blank">&nbsp;</span></td></tr>
<tr><th>TOTAL ASSETS</th><th>$<span class="blank">&nbsp;</span></th><th>$<span class="blank">&nbsp;</span></th></tr>
<tr><th>Liabilities</th><th></th><th></th></tr>
<tr><td>Accounts payable</td><td>$<span class="blank">&nbsp;</span></td><td>$<span class="blank">&nbsp;</span></td></tr>
<tr><td>Loans and other liabilities</td><td>$<span class="blank">&nbsp;</span></td><td>$<span class="blank">&nbsp;</span></td></tr>
<tr><th>TOTAL LIABILITIES</th><th>$<span class="blank">&nbsp;</span></th><th>$<span class="blank">&nbsp;</span></th></tr>
<tr><th>NET ASSETS</th><th>$<span class="blank">&nbsp;</span></th><th>$<span class="blank">&nbsp;</span></th></tr>
</table>

<h2>Part V — Program Service Accomplishments</h2>
<p>Describe your three largest programs by expenses. This is one of the most important sections — be specific about what you did and who you helped.</p>
<div style="background:#f9f9f9;border:1px solid #ddd;padding:1em;margin:.75em 0">
<p><strong>Program 1 (largest by expense):</strong></p>
<p>Description: <em>${a.activities||'[Describe your primary program]'}</em></p>
<p>People served: <em>${a.whoHelp||'[Who benefited]'}</em></p>
<p>Expenses: $<span class="blank">&nbsp;</span> &nbsp; Grants: $<span class="blank">&nbsp;</span> &nbsp; Revenue: $<span class="blank">&nbsp;</span></p>
</div>
<div style="background:#f9f9f9;border:1px solid #ddd;padding:1em;margin:.75em 0">
<p><strong>Program 2:</strong></p>
<p>Description: <span class="blank" style="min-width:400px">&nbsp;</span></p>
<p>Expenses: $<span class="blank">&nbsp;</span></p>
</div>
<div style="background:#f9f9f9;border:1px solid #ddd;padding:1em;margin:.75em 0">
<p><strong>Program 3:</strong></p>
<p>Description: <span class="blank" style="min-width:400px">&nbsp;</span></p>
<p>Expenses: $<span class="blank">&nbsp;</span></p>
</div>

<h2>Part VI — Governance Checklist</h2>
<p>The IRS asks these governance questions on Form 990. Check off your answers:</p>
<table>
<tr><th>Question</th><th>Yes</th><th>No</th></tr>
<tr><td>Did the org have a written conflict of interest policy?</td><td><input type="checkbox"></td><td><input type="checkbox"></td></tr>
<tr><td>Were officers, directors, or key employees listed on the return?</td><td><input type="checkbox"></td><td><input type="checkbox"></td></tr>
<tr><td>Did the org become aware of a significant diversion of assets?</td><td><input type="checkbox"></td><td><input type="checkbox"></td></tr>
<tr><td>Did the org have members or stockholders?</td><td><input type="checkbox"></td><td><input type="checkbox"></td></tr>
<tr><td>Did the org contemporaneously document meetings?</td><td><input type="checkbox"></td><td><input type="checkbox"></td></tr>
<tr><td>Did the org have a written whistleblower policy?</td><td><input type="checkbox"></td><td><input type="checkbox"></td></tr>
<tr><td>Did the org have a document retention and destruction policy?</td><td><input type="checkbox"></td><td><input type="checkbox"></td></tr>
<tr><td>Did any officer, director, or key employee have a family/business relationship with any other?</td><td><input type="checkbox"></td><td><input type="checkbox"></td></tr>
</table>

<h2>Schedule A — Public Support Test</h2>
<div class="info-box">
Public charities must pass the "public support test" — showing that at least 33.3% of their support comes from the general public (not one private source). If you receive most of your funding from one donor, you may be reclassified as a private foundation.
</div>
<table>
<tr><th>Year</th><th>${parseInt(taxYear)-4}</th><th>${parseInt(taxYear)-3}</th><th>${parseInt(taxYear)-2}</th><th>${parseInt(taxYear)-1}</th><th>${taxYear}</th><th>Total</th></tr>
<tr><td>Public support</td><td>$<span class="blank" style="min-width:40px">&nbsp;</span></td><td>$<span class="blank" style="min-width:40px">&nbsp;</span></td><td>$<span class="blank" style="min-width:40px">&nbsp;</span></td><td>$<span class="blank" style="min-width:40px">&nbsp;</span></td><td>$<span class="blank" style="min-width:40px">&nbsp;</span></td><td>$<span class="blank" style="min-width:40px">&nbsp;</span></td></tr>
<tr><td>Total support</td><td></td><td></td><td></td><td></td><td></td><td>$<span class="blank" style="min-width:40px">&nbsp;</span></td></tr>
<tr><td colspan="6"><strong>Public support percentage</strong></td><td><span class="blank" style="min-width:40px">&nbsp;</span>%</td></tr>
</table>

<h2>Filing Deadlines &amp; Key Reminders</h2>
<table>
<tr><th>Item</th><th>Due Date</th><th>Where to File</th></tr>
<tr><td>Form 990-N, 990-EZ, or 990</td><td>${dueDate} (or 15th day of 5th month after fiscal year end)</td><td>IRS.gov (990-N online only; 990/990-EZ via mail or e-file)</td></tr>
<tr><td>State annual report</td><td>Varies by state — see State Report document</td><td>${sd?sd.agency:'Your state agency'}</td></tr>
<tr><td>Charitable solicitation renewal</td><td>${sd&&sd.solicitationReg?'Annual renewal required':'N/A for your state'}</td><td>${sd&&sd.solicitationReg?sd.agency:'N/A'}</td></tr>
<tr><td>State tax exemption renewal</td><td>Varies — check with your state</td><td>${sd?sd.agency:'Your state agency'}</td></tr>
</table>

<div class="err-box">
⚠️ <strong>IMPORTANT:</strong> Failing to file Form 990 for <strong>3 consecutive years</strong> results in automatic revocation of your 501(c)(3) status. Set a recurring calendar reminder for ${dueDate} every year.
</div>

<p style="margin-top:2em">Prepared for: <strong>${orgName}</strong> &nbsp;|&nbsp; Tax Year: <strong>${taxYear}</strong> &nbsp;|&nbsp; Generated by Start Your Cause</p>
` + ydocFooter;
}

// ─────────────────────────────────────────────
// 2. ANNUAL STATE REPORT
// ─────────────────────────────────────────────
function generateStateAnnualReport(a, sd, year) {
  const orgName = a.orgName || "[Organization Name]";
  const taxYear = year || new Date().getFullYear() - 1;
  const stateName = sd ? sd.name : (a.state || "[State]");

  return ydocHeader(
    `Annual State Report Template`,
    `${orgName} | ${stateName} | Year ${taxYear}`
  ) + `

<div class="info-box">
<strong>About this document:</strong> Most states require nonprofits to file an annual or biennial report with the Secretary of State (or equivalent agency). This template helps you gather the information typically required. Always check your state's specific form and deadline — requirements vary significantly.
</div>

${sd ? `
<h2>${sd.name} — Annual Report Requirements</h2>
<table>
<tr><td width="45%">Filing agency</td><td><strong>${sd.agency}</strong></td></tr>
<tr><td>Agency website</td><td><a href="${sd.agencyUrl}">${sd.agencyUrl}</a></td></tr>
<tr><td>Solicitation registration renewal</td><td>${sd.solicitationReg ? `Required annually — Fee: $${sd.solicitationFee||0}` : 'Not required in your state'}</td></tr>
<tr><td>Processing time</td><td>${sd.processingDays} business days</td></tr>
</table>
${sd.unique&&sd.unique.length?`<div class="warn-box"><strong>⚠️ ${sd.name}-specific reminders:</strong><ul style="margin:.5em 0 0;padding-left:1.25em">${sd.unique.map(u=>`<li>${u}</li>`).join('')}</ul></div>`:''}
` : ''}

<h2>Section 1 — Organization Information</h2>
<table class="no-border">
<tr><td width="45%">Legal name</td><td><strong>${orgName}</strong></td></tr>
<tr><td>EIN</td><td><span class="blank">&nbsp;</span></td></tr>
<tr><td>State registration number</td><td><span class="blank">&nbsp;</span></td></tr>
<tr><td>Principal office address</td><td>${a.address||'<span class="blank" style="min-width:300px">&nbsp;</span>'}</td></tr>
<tr><td>Phone number</td><td><span class="blank">&nbsp;</span></td></tr>
<tr><td>Email</td><td>${a.founderEmail||'<span class="blank">&nbsp;</span>'}</td></tr>
<tr><td>Website</td><td>https://startyourcause.org</td></tr>
<tr><td>Date incorporated</td><td><span class="blank">&nbsp;</span></td></tr>
<tr><td>State of incorporation</td><td>${stateName}</td></tr>
<tr><td>Fiscal year end</td><td>${a.fiscal||'December 31'}</td></tr>
</table>

<h2>Section 2 — Current Officers and Directors</h2>
<table>
<tr><th>Name</th><th>Title</th><th>Address</th><th>Compensation</th></tr>
<tr><td>${a.founderName||'<span class="blank">&nbsp;</span>'}</td><td>President / Founder</td><td><span class="blank">&nbsp;</span></td><td>$<span class="blank" style="min-width:60px">&nbsp;</span></td></tr>
<tr><td>${a.board2||'<span class="blank">&nbsp;</span>'}</td><td><span class="blank">&nbsp;</span></td><td><span class="blank">&nbsp;</span></td><td>$<span class="blank" style="min-width:60px">&nbsp;</span></td></tr>
<tr><td>${a.board3||'<span class="blank">&nbsp;</span>'}</td><td><span class="blank">&nbsp;</span></td><td><span class="blank">&nbsp;</span></td><td>$<span class="blank" style="min-width:60px">&nbsp;</span></td></tr>
${a.board4?`<tr><td>${a.board4}</td><td><span class="blank">&nbsp;</span></td><td><span class="blank">&nbsp;</span></td><td>$<span class="blank" style="min-width:60px">&nbsp;</span></td></tr>`:''}
${a.board5?`<tr><td>${a.board5}</td><td><span class="blank">&nbsp;</span></td><td><span class="blank">&nbsp;</span></td><td>$<span class="blank" style="min-width:60px">&nbsp;</span></td></tr>`:''}
<tr><td><span class="blank">&nbsp;</span></td><td><span class="blank">&nbsp;</span></td><td><span class="blank">&nbsp;</span></td><td>$<span class="blank" style="min-width:60px">&nbsp;</span></td></tr>
</table>

<h2>Section 3 — Registered Agent</h2>
<table class="no-border">
<tr><td width="45%">Registered agent name</td><td><span class="blank" style="min-width:260px">&nbsp;</span></td></tr>
<tr><td>Registered agent address</td><td><span class="blank" style="min-width:300px">&nbsp;</span></td></tr>
<tr><td>City, State, ZIP</td><td><span class="blank" style="min-width:300px">&nbsp;</span></td></tr>
</table>

<h2>Section 4 — Activity Summary for ${taxYear}</h2>
<table class="no-border">
<tr><td width="45%">Primary programs operated</td><td><em>${a.activities||'[Describe programs]'}</em></td></tr>
<tr><td>People/organizations served</td><td>${a.howMany||'<span class="blank">&nbsp;</span>'}</td></tr>
<tr><td>Geographic area served</td><td>${a.location||'<span class="blank">&nbsp;</span>'}</td></tr>
<tr><td>Any changes to mission or activities?</td><td>☐ Yes &nbsp; ☐ No &nbsp; If yes: <span class="blank" style="min-width:180px">&nbsp;</span></td></tr>
<tr><td>Any changes to board or officers?</td><td>☐ Yes &nbsp; ☐ No &nbsp; If yes: <span class="blank" style="min-width:180px">&nbsp;</span></td></tr>
<tr><td>Any changes to address?</td><td>☐ Yes &nbsp; ☐ No &nbsp; If yes: <span class="blank" style="min-width:180px">&nbsp;</span></td></tr>
</table>

<h2>Section 5 — Financial Summary for ${taxYear}</h2>
<table>
<tr><th>Category</th><th>Amount</th></tr>
<tr><td>Total revenue</td><td>$<span class="blank" style="min-width:120px">&nbsp;</span></td></tr>
<tr><td>Total expenses</td><td>$<span class="blank" style="min-width:120px">&nbsp;</span></td></tr>
<tr><td>Net assets (end of year)</td><td>$<span class="blank" style="min-width:120px">&nbsp;</span></td></tr>
<tr><td>Total assets</td><td>$<span class="blank" style="min-width:120px">&nbsp;</span></td></tr>
<tr><td>Total liabilities</td><td>$<span class="blank" style="min-width:120px">&nbsp;</span></td></tr>
</table>

<h2>Section 6 — Charitable Solicitation Renewal</h2>
${sd && sd.solicitationReg ? `
<div class="warn-box">⚠️ <strong>${sd.name} requires annual charitable solicitation renewal.</strong> You must renew before the deadline or you will be prohibited from fundraising in ${sd.name}.</div>
<table class="no-border">
<tr><td width="45%">Renewal fee</td><td><strong>$${sd.solicitationFee||0}</strong></td></tr>
<tr><td>File with</td><td>${sd.agency}</td></tr>
<tr><td>Total gross contributions received in ${taxYear}</td><td>$<span class="blank">&nbsp;</span></td></tr>
<tr><td>Did you use a professional fundraiser?</td><td>☐ Yes &nbsp; ☐ No</td></tr>
</table>` : `<p style="color:#666">Your state (${stateName}) does not require charitable solicitation registration or renewal. No action needed.</p>`}

<h2>Annual Compliance Checklist for ${taxYear}</h2>
<table>
<tr><th>Task</th><th>Due Date</th><th>Done?</th></tr>
<tr><td>File IRS Form 990/990-EZ/990-N</td><td>May 15, ${parseInt(taxYear)+1}</td><td><input type="checkbox"></td></tr>
<tr><td>File state annual report</td><td><span class="blank">&nbsp;</span></td><td><input type="checkbox"></td></tr>
${sd&&sd.solicitationReg?`<tr><td>Renew charitable solicitation registration</td><td><span class="blank">&nbsp;</span></td><td><input type="checkbox"></td></tr>`:''}
<tr><td>Hold annual board meeting</td><td><span class="blank">&nbsp;</span></td><td><input type="checkbox"></td></tr>
<tr><td>Review and update conflict of interest disclosures</td><td>Annually</td><td><input type="checkbox"></td></tr>
<tr><td>Review bylaws for needed updates</td><td>Annually</td><td><input type="checkbox"></td></tr>
<tr><td>Update board roster if members changed</td><td>As needed</td><td><input type="checkbox"></td></tr>
<tr><td>Review registered agent information</td><td>Annually</td><td><input type="checkbox"></td></tr>
<tr><td>Renew state tax exemption (if required)</td><td>Varies</td><td><input type="checkbox"></td></tr>
</table>

<p style="margin-top:2em">Prepared for: <strong>${orgName}</strong> &nbsp;|&nbsp; State: <strong>${stateName}</strong> &nbsp;|&nbsp; Year: <strong>${taxYear}</strong></p>
` + ydocFooter;
}

// ─────────────────────────────────────────────
// 3. ANNUAL BOARD MEETING MINUTES
// ─────────────────────────────────────────────
function generateAnnualMinutes(a, sd, year) {
  const orgName = a.orgName || "[Organization Name]";
  const taxYear = year || new Date().getFullYear() - 1;
  const currentYear = parseInt(taxYear) + 1;

  return ydocHeader(
    `Annual Meeting of the Board of Directors`,
    `${orgName} | For the Year Ended December 31, ${taxYear}`
  ) + `

<p><strong>Date:</strong> <span class="blank">&nbsp;</span> &nbsp;&nbsp; <strong>Time:</strong> <span class="blank">&nbsp;</span> &nbsp;&nbsp; <strong>Location:</strong> <span class="blank" style="min-width:220px">&nbsp;</span></p>
<p><strong>Meeting called by:</strong> ${a.founderName||'[President Name]'}</p>

<h2>I. Call to Order and Attendance</h2>
<p>The annual meeting of the Board of Directors of <strong>${orgName}</strong> was called to order by ${a.founderName||'[President]'} at <span class="blank" style="min-width:60px">&nbsp;</span> on <span class="blank" style="min-width:120px">&nbsp;</span>.</p>
<p><strong>Directors present:</strong></p>
<table>
<tr><th>Name</th><th>Role</th><th>Present</th><th>Absent/Excused</th></tr>
<tr><td>${a.founderName||'[Name]'}</td><td>President</td><td><input type="checkbox"></td><td><input type="checkbox"></td></tr>
<tr><td>${a.board2||'[Name]'}</td><td>Vice President / Director</td><td><input type="checkbox"></td><td><input type="checkbox"></td></tr>
<tr><td>${a.board3||'[Name]'}</td><td>Secretary / Director</td><td><input type="checkbox"></td><td><input type="checkbox"></td></tr>
${a.board4?`<tr><td>${a.board4}</td><td>Director</td><td><input type="checkbox"></td><td><input type="checkbox"></td></tr>`:''}
${a.board5?`<tr><td>${a.board5}</td><td>Director</td><td><input type="checkbox"></td><td><input type="checkbox"></td></tr>`:''}
<tr><td><span class="blank">&nbsp;</span></td><td>Director</td><td><input type="checkbox"></td><td><input type="checkbox"></td></tr>
</table>
<p>A quorum ☐ was &nbsp; ☐ was not &nbsp; present. Total directors present: <span class="blank" style="min-width:40px">&nbsp;</span> of <span class="blank" style="min-width:40px">&nbsp;</span></p>
<p>Others present: <span class="blank" style="min-width:300px">&nbsp;</span></p>

<h2>II. Approval of Previous Meeting Minutes</h2>
<p>The minutes of the previous board meeting held on <span class="blank" style="min-width:120px">&nbsp;</span> were reviewed.</p>
<p>Motion to approve: <span class="blank">&nbsp;</span> &nbsp; Seconded by: <span class="blank">&nbsp;</span></p>
<p>Vote: &nbsp; Ayes <span class="blank" style="min-width:30px">&nbsp;</span> &nbsp; Nays <span class="blank" style="min-width:30px">&nbsp;</span> &nbsp; Abstentions <span class="blank" style="min-width:30px">&nbsp;</span> &nbsp; ☐ Approved &nbsp; ☐ Denied</p>

<h2>III. President's Report — Year in Review (${taxYear})</h2>
<p>President ${a.founderName||'[Name]'} presented an overview of the organization's activities and accomplishments for the year ended December 31, ${taxYear}:</p>
<p><em>${a.activities||'[Describe major accomplishments, programs run, milestones reached]'}</em></p>
<p>People/organizations served in ${taxYear}: <strong>${a.howMany||'<span class="blank">&nbsp;</span>'}</strong></p>
<p>Major accomplishments: <span class="blank" style="min-width:400px">&nbsp;</span></p>
<p>Challenges faced: <span class="blank" style="min-width:400px">&nbsp;</span></p>

<h2>IV. Treasurer's Financial Report (${taxYear})</h2>
<p>The Treasurer presented the following financial summary for the year ended December 31, ${taxYear}:</p>
<table>
<tr><th>Category</th><th>Budget</th><th>Actual</th><th>Variance</th></tr>
<tr><td>Total Revenue</td><td>$<span class="blank">&nbsp;</span></td><td>$<span class="blank">&nbsp;</span></td><td>$<span class="blank">&nbsp;</span></td></tr>
<tr><td>Total Expenses</td><td>$<span class="blank">&nbsp;</span></td><td>$<span class="blank">&nbsp;</span></td><td>$<span class="blank">&nbsp;</span></td></tr>
<tr><td>Net Income / (Deficit)</td><td>$<span class="blank">&nbsp;</span></td><td>$<span class="blank">&nbsp;</span></td><td>$<span class="blank">&nbsp;</span></td></tr>
<tr><td>Cash on Hand (End of Year)</td><td></td><td>$<span class="blank">&nbsp;</span></td><td></td></tr>
</table>
<p>Motion to accept financial report: <span class="blank">&nbsp;</span> &nbsp; Seconded by: <span class="blank">&nbsp;</span></p>
<p>Vote: &nbsp; Ayes <span class="blank" style="min-width:30px">&nbsp;</span> &nbsp; Nays <span class="blank" style="min-width:30px">&nbsp;</span> &nbsp; ☐ Approved</p>

<h2>V. IRS Form 990 Filing</h2>
<p>The Board reviewed the IRS Form 990 (or 990-EZ / 990-N) for tax year ${taxYear}, due May 15, ${currentYear}.</p>
<p>Form type to be filed: &nbsp; ☐ 990-N &nbsp; ☐ 990-EZ &nbsp; ☐ 990 &nbsp; ☐ 990-PF</p>
<p>Prepared by: <span class="blank" style="min-width:200px">&nbsp;</span> &nbsp; Filing deadline: May 15, ${currentYear}</p>
<p>Motion to authorize filing: <span class="blank">&nbsp;</span> &nbsp; Seconded: <span class="blank">&nbsp;</span></p>
<p>Vote: &nbsp; Ayes <span class="blank" style="min-width:30px">&nbsp;</span> &nbsp; Nays <span class="blank" style="min-width:30px">&nbsp;</span> &nbsp; ☐ Approved</p>

<h2>VI. State Annual Report</h2>
<p>The Board authorized the filing of the annual report with ${sd?sd.agency:'the state agency'} for the year ${taxYear}.</p>
${sd&&sd.solicitationReg?`<p>The Board also authorized renewal of the charitable solicitation registration in ${sd.name}. Renewal fee: $${sd.solicitationFee||0}.</p>`:''}
<p>Motion to authorize: <span class="blank">&nbsp;</span> &nbsp; Seconded: <span class="blank">&nbsp;</span></p>
<p>Vote: &nbsp; Ayes <span class="blank" style="min-width:30px">&nbsp;</span> &nbsp; Nays <span class="blank" style="min-width:30px">&nbsp;</span> &nbsp; ☐ Approved</p>

<h2>VII. Election of Officers for ${currentYear}</h2>
<p>The following officers were elected/re-elected for the coming year:</p>
<table>
<tr><th>Office</th><th>Incumbent</th><th>Nominated</th><th>Vote</th></tr>
<tr><td>President</td><td>${a.founderName||'[Name]'}</td><td><span class="blank">&nbsp;</span></td><td>Ayes <span class="blank" style="min-width:30px">&nbsp;</span> Nays <span class="blank" style="min-width:30px">&nbsp;</span></td></tr>
<tr><td>Vice President</td><td>${a.board2||'[Name]'}</td><td><span class="blank">&nbsp;</span></td><td>Ayes <span class="blank" style="min-width:30px">&nbsp;</span> Nays <span class="blank" style="min-width:30px">&nbsp;</span></td></tr>
<tr><td>Secretary</td><td>${a.board3||'[Name]'}</td><td><span class="blank">&nbsp;</span></td><td>Ayes <span class="blank" style="min-width:30px">&nbsp;</span> Nays <span class="blank" style="min-width:30px">&nbsp;</span></td></tr>
<tr><td>Treasurer</td><td>${a.board4||a.board2||'[Name]'}</td><td><span class="blank">&nbsp;</span></td><td>Ayes <span class="blank" style="min-width:30px">&nbsp;</span> Nays <span class="blank" style="min-width:30px">&nbsp;</span></td></tr>
</table>

<h2>VIII. Budget Approval for ${currentYear}</h2>
<p>The Treasurer presented the proposed budget for the fiscal year ${currentYear}:</p>
<table>
<tr><th>Category</th><th>Proposed ${currentYear}</th><th>Actual ${taxYear}</th></tr>
<tr><td>Total projected revenue</td><td>$<span class="blank">&nbsp;</span></td><td>$<span class="blank">&nbsp;</span></td></tr>
<tr><td>Total projected expenses</td><td>$<span class="blank">&nbsp;</span></td><td>$<span class="blank">&nbsp;</span></td></tr>
<tr><td>Program expenses</td><td>$<span class="blank">&nbsp;</span></td><td></td></tr>
<tr><td>Administrative expenses</td><td>$<span class="blank">&nbsp;</span></td><td></td></tr>
<tr><td>Fundraising expenses</td><td>$<span class="blank">&nbsp;</span></td><td></td></tr>
</table>
<p>Motion to approve budget: <span class="blank">&nbsp;</span> &nbsp; Seconded: <span class="blank">&nbsp;</span></p>
<p>Vote: &nbsp; Ayes <span class="blank" style="min-width:30px">&nbsp;</span> &nbsp; Nays <span class="blank" style="min-width:30px">&nbsp;</span> &nbsp; ☐ Approved</p>

<h2>IX. Conflict of Interest Disclosures</h2>
<p>Each board member was asked to disclose any conflicts of interest for the coming year. The following disclosures were made:</p>
<p>Disclosures: &nbsp; ☐ None &nbsp; ☐ See attached disclosure forms</p>
<p>All directors confirmed they have read and agreed to abide by the Conflict of Interest Policy.</p>

<h2>X. Old Business</h2>
<p><span class="blank" style="min-width:500px">&nbsp;</span></p>
<p><span class="blank" style="min-width:500px">&nbsp;</span></p>

<h2>XI. New Business</h2>
<p><span class="blank" style="min-width:500px">&nbsp;</span></p>
<p><span class="blank" style="min-width:500px">&nbsp;</span></p>

<h2>XII. Next Meeting</h2>
<p>The next regular meeting of the Board shall be held on: <span class="blank" style="min-width:200px">&nbsp;</span></p>

<h2>XIII. Adjournment</h2>
<p>There being no further business, the meeting was adjourned at <span class="blank" style="min-width:60px">&nbsp;</span>.</p>

<p style="margin-top:3em">Respectfully submitted,</p>
<div style="margin-top:2em;display:flex;gap:4em;flex-wrap:wrap">
<div><div class="sig-line">Secretary</div><p>${a.board3||'[Secretary Name]'}</p><p>Date: <span class="blank" style="min-width:100px">&nbsp;</span></p></div>
<div><div class="sig-line">President</div><p>${a.founderName||'[President Name]'}</p><p>Date: <span class="blank" style="min-width:100px">&nbsp;</span></p></div>
</div>
` + ydocFooter;
}

// ─────────────────────────────────────────────
// 4. DONOR ACKNOWLEDGMENT LETTERS
// ─────────────────────────────────────────────
function generateDonorLetters(a, year) {
  const orgName = a.orgName || "[Organization Name]";
  const taxYear = year || new Date().getFullYear() - 1;
  const founder = a.founderName || "[Executive Director]";

  return ydocHeader(
    `Donor Acknowledgment Letter Templates`,
    `${orgName} | IRS-Compliant Gift Acknowledgment Letters`
  ) + `

<div class="info-box">
<strong>IRS Requirements for Donor Acknowledgment:</strong><br>
• For any donation of <strong>$250 or more</strong>, the IRS requires a written acknowledgment from your organization — otherwise the donor CANNOT claim a tax deduction.<br>
• The letter must include: (1) your org name and EIN, (2) date of donation, (3) amount donated or description of non-cash gift, (4) statement of whether any goods or services were provided in exchange.<br>
• For donations under $250, a bank record or receipt is sufficient, but a letter builds donor relationships.
</div>

<div class="warn-box">
⚠️ Send acknowledgment letters as soon as possible after receiving a gift — ideally within 2 weeks. Letters MUST be sent before the donor files their tax return (typically April 15 of the following year).
</div>

<hr style="margin:2em 0;border:none;border-top:2px solid #ccc">
<h2>Template 1 — Single Cash Donation ($250 or more)</h2>
<hr style="margin:.5em 0 1.5em;border:none;border-top:1px solid #eee">

<p>[Date]</p>
<p>[Donor Name]<br>[Donor Address]<br>[City, State, ZIP]</p>
<p>Dear [Donor Name],</p>
<p>On behalf of <strong>${orgName}</strong>, I want to express our sincere gratitude for your generous donation of <strong>$[Amount]</strong> received on <strong>[Date of Gift]</strong>.</p>
<p>Your support directly helps us ${a.activities ? a.activities.substring(0,120)+'...' : '[describe your mission and impact]'}. Because of donors like you, we are able to serve ${a.whoHelp ? a.whoHelp.substring(0,100)+'...' : '[who you serve]'} in ${a.location||'our community'}.</p>
<p>This letter serves as your official tax receipt. Please retain it for your records. <strong>${orgName}</strong> is a 501(c)(3) tax-exempt organization (EIN: <span class="blank" style="min-width:100px">&nbsp;</span>). <strong>No goods or services were provided in exchange for this contribution.</strong> Your donation is tax-deductible to the fullest extent permitted by law.</p>
<p>With gratitude,</p>
<div style="margin-top:2em">
<div class="sig-line">Signature</div>
<p>${founder}<br>President / Executive Director<br>${orgName}<br>${a.founderEmail||'[Email]'}</p>
</div>

<hr style="margin:3em 0 2em;border:none;border-top:2px solid #ccc">
<h2>Template 2 — Recurring / Monthly Donor</h2>
<hr style="margin:.5em 0 1.5em;border:none;border-top:1px solid #eee">

<p>[Date — send annually in January to cover prior year]</p>
<p>[Donor Name]<br>[Donor Address]</p>
<p>Dear [Donor Name],</p>
<p>Thank you so much for your ongoing commitment to <strong>${orgName}</strong>. Your monthly support throughout ${taxYear} has made an incredible difference.</p>
<p>This letter serves as your annual summary acknowledgment for tax purposes. During ${taxYear}, you made the following contributions:</p>
<table>
<tr><th>Date</th><th>Amount</th><th>Payment Method</th></tr>
<tr><td>[Month] 1, ${taxYear}</td><td>$<span class="blank" style="min-width:60px">&nbsp;</span></td><td><span class="blank">&nbsp;</span></td></tr>
<tr><td>[Month] 1, ${taxYear}</td><td>$<span class="blank" style="min-width:60px">&nbsp;</span></td><td><span class="blank">&nbsp;</span></td></tr>
<tr><td>[Month] 1, ${taxYear}</td><td>$<span class="blank" style="min-width:60px">&nbsp;</span></td><td><span class="blank">&nbsp;</span></td></tr>
<tr><th>TOTAL ${taxYear}</th><th>$<span class="blank" style="min-width:60px">&nbsp;</span></th><th></th></tr>
</table>
<p><strong>${orgName}</strong> is a 501(c)(3) organization (EIN: <span class="blank" style="min-width:100px">&nbsp;</span>). <strong>No goods or services were provided in exchange for these contributions.</strong> Your donations are tax-deductible to the fullest extent permitted by law.</p>
<p>With deepest gratitude,</p>
<div style="margin-top:2em">
<div class="sig-line">Signature</div>
<p>${founder}<br>President / Executive Director<br>${orgName}</p>
</div>

<hr style="margin:3em 0 2em;border:none;border-top:2px solid #ccc">
<h2>Template 3 — In-Kind (Non-Cash) Donation</h2>
<hr style="margin:.5em 0 1.5em;border:none;border-top:1px solid #eee">

<div class="warn-box">⚠️ For non-cash donations: your organization acknowledges receipt and describes the item but does <strong>NOT</strong> assign a dollar value. The donor is responsible for determining the fair market value for tax purposes. For gifts over $500, the donor must complete IRS Form 8283. For gifts over $5,000, the donor must obtain a qualified appraisal.</div>

<p>[Date]</p>
<p>[Donor Name]<br>[Donor Address]</p>
<p>Dear [Donor Name],</p>
<p>Thank you for your generous in-kind donation to <strong>${orgName}</strong>. We are grateful for your support of our mission.</p>
<p>On <strong>[Date of Gift]</strong>, we received the following item(s) from you:</p>
<table>
<tr><th>Description of Item(s)</th><th>Condition</th></tr>
<tr><td><span class="blank" style="min-width:300px">&nbsp;</span></td><td><span class="blank">&nbsp;</span></td></tr>
<tr><td><span class="blank" style="min-width:300px">&nbsp;</span></td><td><span class="blank">&nbsp;</span></td></tr>
</table>
<p><strong>${orgName}</strong> did not provide any goods or services in exchange for this donation. No value has been assigned to the donated item(s) by ${orgName} — the donor is responsible for determining fair market value for tax deduction purposes.</p>
<p><strong>${orgName}</strong> is a 501(c)(3) tax-exempt organization. EIN: <span class="blank" style="min-width:100px">&nbsp;</span></p>
<p>Sincerely,</p>
<div style="margin-top:2em">
<div class="sig-line">Signature</div>
<p>${founder}<br>President / Executive Director<br>${orgName}</p>
</div>

<hr style="margin:3em 0 2em;border:none;border-top:2px solid #ccc">
<h2>Template 4 — Event/Auction Donation (Goods/Services Provided)</h2>
<hr style="margin:.5em 0 1.5em;border:none;border-top:1px solid #eee">

<div class="info-box">Use this when donors receive something of value at an event (dinner ticket, auction item, etc.). Only the amount ABOVE the fair market value of what was received is tax-deductible.</div>

<p>[Date]</p>
<p>[Donor Name]<br>[Donor Address]</p>
<p>Dear [Donor Name],</p>
<p>Thank you for your support of <strong>${orgName}</strong> at our [Event Name] on [Date of Event].</p>
<p>You paid <strong>$[Total Amount Paid]</strong> for [description of ticket/item purchased].</p>
<p>The estimated fair market value of the goods/services you received was <strong>$[Fair Market Value]</strong>.</p>
<p>Therefore, the <strong>tax-deductible portion</strong> of your payment is <strong>$[Amount Paid minus Fair Market Value]</strong>.</p>
<p><strong>${orgName}</strong> is a 501(c)(3) tax-exempt organization (EIN: <span class="blank" style="min-width:100px">&nbsp;</span>).</p>
<p>Thank you again for your generous support!</p>
<div style="margin-top:2em">
<div class="sig-line">Signature</div>
<p>${founder}<br>President / Executive Director<br>${orgName}</p>
</div>

<hr style="margin:3em 0 2em;border:none;border-top:2px solid #ccc">
<h2>Template 5 — Year-End Thank You &amp; Tax Summary</h2>
<hr style="margin:.5em 0 1.5em;border:none;border-top:1px solid #eee">

<p>January [Date], ${parseInt(taxYear)+1}</p>
<p>[Donor Name]<br>[Donor Address]</p>
<p>Dear [Donor Name],</p>
<p>As we begin a new year, we want to take a moment to thank you for your extraordinary support of <strong>${orgName}</strong> in ${taxYear}.</p>
<p>Because of donors like you, this year we were able to:</p>
<ul>
<li><span class="blank" style="min-width:400px">&nbsp;</span></li>
<li><span class="blank" style="min-width:400px">&nbsp;</span></li>
<li><span class="blank" style="min-width:400px">&nbsp;</span></li>
</ul>
<p>Your total tax-deductible contributions to ${orgName} in ${taxYear} were: <strong>$[Total Amount]</strong></p>
<p>This letter serves as your official year-end tax summary. Please retain it for your ${taxYear} tax return. <strong>${orgName}</strong> is a 501(c)(3) organization (EIN: <span class="blank" style="min-width:100px">&nbsp;</span>). No goods or services were provided in exchange for your contributions unless otherwise noted above.</p>
<p>We are deeply grateful for your partnership in our mission. With your continued support, ${parseInt(taxYear)+1} will be even more impactful.</p>
<p>With heartfelt thanks,</p>
<div style="margin-top:2em">
<div class="sig-line">Signature</div>
<p>${founder}<br>President / Executive Director<br>${orgName}<br>${a.founderEmail||'[Email]'}</p>
</div>
` + ydocFooter;
}
